package hardwrap_test

// The generated-document exemption: the one way out of this rule, and so the one
// place an evasion is worth the most. Every case here is a shape that either IS
// a generator's claim of authorship or merely looks like one, and the second
// half is the half that matters.

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestAGeneratedDocumentIsOutOfScopeEntirely pins the ratified scope: the rule
// is about hand-maintained prose. Reporting a generated file tells an author to
// reflow a document the next run overwrites.
func TestAGeneratedDocumentIsOutOfScopeEntirely(t *testing.T) {
	t.Parallel()

	for _, claim := range []string{
		"<!-- Code generated by tool. DO NOT EDIT. -->",
		"<!-- Code generated by gomarkdoc. DO NOT EDIT -->",
		"<!-- @generated -->",
		"<!--\n@generated\n-->",
	} {
		assert.Empty(
			t,
			analyze(t, "api.md", claim+"\n\nwrapped one\nwrapped two\n"),
			"%s is a generator's claim",
			claim,
		)
	}
}

// TestOnlyAnInvisibleClaimExemptsADocument pins the attack surface of that
// exemption. Every shape here puts the same words where a READER sees them, and
// accepting one would be a one-line, audit-trail-free opt-out from every
// finding in the file.
func TestOnlyAnInvisibleClaimExemptsADocument(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"prose":            "@generated",
		"a fenced example": "```\n<!-- @generated -->\n```",
		"an indented one":  "    <!-- @generated -->",
		"a list item":      "- <!-- @generated -->",
		"a quotation":      "> <!-- @generated -->",
		"a heading":        "# Code generated by hand. DO NOT EDIT.",
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%s is visible, so it is not a generator's claim", name)
	}
}

// TestAClaimOutsideTheCommentIsNotAClaim pins the hole an adversarial review
// found. A CommonMark comment block ends at the line holding `-->`, and the
// REST of that line belongs to the block — so the words can sit outside the
// comment while the block is still a comment block. One of these renders an
// empty span and the other renders the words as visible text, and each was a
// one-line, audit-trail-free opt-out from every finding in the file.
func TestAClaimOutsideTheCommentIsNotAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"hidden in an attribute":   `<!-- --><span title="@generated"></span>`,
		"visible after the closer": "<!-- x --> @generated",
		"in an image alt":          `<!-- --><img src="x.png" alt="a picture" data-k="@generated">`,
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%s is outside the comment", name)
	}
}

// TestOnlyACommentBlockCanCarryTheClaim pins the block TYPE. An ordinary HTML
// block is visible markup a reader sees; only the comment renders as nothing,
// and a claim inside a `<div>` is one anybody can type into a document.
func TestOnlyACommentBlockCanCarryTheClaim(t *testing.T) {
	t.Parallel()

	assert.NotEmpty(t, analyze(t, "notes.md", "<div>@generated</div>\n\nwrapped one\nwrapped two\n"))
}

// TestTheClaimIsAGeneratorsAndNotAnAuthorsRequest pins the vocabulary. "DO NOT
// EDIT" is three words any author can type, and "Code generated" without them
// is not the conventional claim either — accepting either would excuse a
// hand-written document on its own say-so.
func TestTheClaimIsAGeneratorsAndNotAnAuthorsRequest(t *testing.T) {
	t.Parallel()

	for _, header := range []string{
		"<!-- DO NOT EDIT -->",
		"<!-- Code generated by hand -->",
		"<!-- generated -->",
		"<!-- MANUAL ADDITIONS BELOW -->",
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%q is not a generator's claim of authorship", header)
	}
}

// TestTheHeaderBoundaryIsExact pins where a claim stops being a statement about
// the FILE and becomes a note beside a passage. One line either side of the
// boundary is what tells a `<=` from a `<`.
func TestTheHeaderBoundaryIsExact(t *testing.T) {
	t.Parallel()

	const body = "\n\nwrapped one\nwrapped two\n"

	assert.Empty(t, analyze(t, "notes.md", "\n\n\n\n<!-- @generated -->"+body),
		"a claim on the last line of the header is the generator's")
	assert.NotEmpty(t, analyze(t, "notes.md", "\n\n\n\n\n<!-- @generated -->"+body),
		"one line further down it is a note about a passage")
}
