package hardwrap_test

// The generated-document exemption: the one way out of this rule, and so the one
// place an evasion is worth the most. Every case here is a shape that either IS
// a generator's claim of authorship or merely looks like one, and the second
// half is the half that matters.

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestAGeneratedDocumentIsOutOfScopeEntirely pins the ratified scope: the rule
// is about hand-maintained prose. Reporting a generated file tells an author to
// reflow a document the next run overwrites.
func TestAGeneratedDocumentIsOutOfScopeEntirely(t *testing.T) {
	t.Parallel()

	for _, claim := range []string{
		"<!-- Code generated by tool. DO NOT EDIT. -->",
		"<!-- Code generated by gomarkdoc. DO NOT EDIT -->",
		"<!-- @generated -->",
		"<!--\n@generated\n-->",
	} {
		assert.Empty(
			t,
			analyze(t, "api.md", claim+"\n\nwrapped one\nwrapped two\n"),
			"%s is a generator's claim",
			claim,
		)
	}
}

// TestOnlyAnInvisibleClaimExemptsADocument pins the attack surface of that
// exemption. Every shape here puts the same words where a READER sees them, and
// accepting one would be a one-line, audit-trail-free opt-out from every
// finding in the file.
func TestOnlyAnInvisibleClaimExemptsADocument(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"prose":            "@generated",
		"a fenced example": "```\n<!-- @generated -->\n```",
		"an indented one":  "    <!-- @generated -->",
		"a list item":      "- <!-- @generated -->",
		"a quotation":      "> <!-- @generated -->",
		"a heading":        "# Code generated by hand. DO NOT EDIT.",
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%s is visible, so it is not a generator's claim", name)
	}
}

// TestAClaimOutsideTheCommentIsNotAClaim pins the hole an adversarial review
// found. A CommonMark comment block ends at the line holding `-->`, and the
// REST of that line belongs to the block — so the words can sit outside the
// comment while the block is still a comment block. One of these renders an
// empty span and the other renders the words as visible text, and each was a
// one-line, audit-trail-free opt-out from every finding in the file.
func TestAClaimOutsideTheCommentIsNotAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"hidden in an attribute":   `<!-- --><span title="@generated"></span>`,
		"visible after the closer": "<!-- x --> @generated",
		"in an image alt":          `<!-- --><img src="x.png" alt="a picture" data-k="@generated">`,
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%s is outside the comment", name)
	}
}

// TestOnlyACommentBlockCanCarryTheClaim pins the block TYPE. An ordinary HTML
// block is visible markup a reader sees; only the comment renders as nothing,
// and a claim inside a `<div>` is one anybody can type into a document.
func TestOnlyACommentBlockCanCarryTheClaim(t *testing.T) {
	t.Parallel()

	assert.NotEmpty(t, analyze(t, "notes.md", "<div>@generated</div>\n\nwrapped one\nwrapped two\n"))
}

// TestTheClaimIsAGeneratorsAndNotAnAuthorsRequest pins the vocabulary. "DO NOT
// EDIT" is three words any author can type, and "Code generated" without them
// is not the conventional claim either — accepting either would excuse a
// hand-written document on its own say-so.
func TestTheClaimIsAGeneratorsAndNotAnAuthorsRequest(t *testing.T) {
	t.Parallel()

	for _, header := range []string{
		"<!-- DO NOT EDIT -->",
		"<!-- Code generated by hand -->",
		"<!-- generated -->",
		"<!-- MANUAL ADDITIONS BELOW -->",
	} {
		assert.NotEmpty(t, analyze(t, "notes.md", header+"\n\nwrapped one\nwrapped two\n"),
			"%q is not a generator's claim of authorship", header)
	}
}

// TestTheHeaderBoundaryIsExact pins where a claim stops being a statement about
// the FILE and becomes a note beside a passage. One line either side of the
// boundary is what tells a `<=` from a `<`.
func TestTheHeaderBoundaryIsExact(t *testing.T) {
	t.Parallel()

	const body = "\n\nwrapped one\nwrapped two\n"

	assert.Empty(t, analyze(t, "notes.md", "\n\n\n\n<!-- @generated -->"+body),
		"a claim on the last line of the header is the generator's")
	assert.NotEmpty(t, analyze(t, "notes.md", "\n\n\n\n\n<!-- @generated -->"+body),
		"one line further down it is a note about a passage")
}

// TestOnlyAnHtmlCommentBlockCanCarryTheClaim pins the invisible-block table in
// the direction nothing in this repository pinned it: ADMITTING a type.
//
// CommonMark has seven HTML block types and exactly one renders as nothing at
// all. Admitting any other left `make check` at exit 0 and total coverage
// 100.0% with every existing case unchanged, because the table is a map literal
// and a changed value adds no statement to reach — and the widening is real:
// under it a `<div>` or a `<foo>` wrapping a genuine comment silences every
// finding in the file, since the wrapper CONTAINS the comment and so the claim
// still matches its interior. That turns the one whole-file exemption into a
// construct a reader sees, which is the opposite of what makes it safe. Found
// by an adversarial review.
//
// Type 4 — a `<!DECLARATION>` — is absent from this table and takes no case:
// the block ends at the first line holding `>`, which no construction can push
// past a claim's own `-->`, so admitting it silences nothing. That is dead
// defensive code rather than an untested branch, and a case that cannot
// discriminate is decoration.
func TestOnlyAnHtmlCommentBlockCanCarryTheClaim(t *testing.T) {
	t.Parallel()

	const claim = "<!-- Code generated by tool. DO NOT EDIT. -->"

	for name, wrapper := range map[string][2]string{
		"a script block (type 1)":           {"<script>", "</script>"},
		"a pre block (type 1)":              {"<pre>", "</pre>"},
		"a processing instruction (type 3)": {"<?php", "?>"},
		"a CDATA section (type 5)":          {"<![CDATA[", "]]>"},
		"a known block tag (type 6)":        {"<div>", "</div>"},
		"any other tag (type 7)":            {"<foo>", "</foo>"},
	} {
		assert.Len(
			t,
			analyze(t, "api.md", wrapper[0]+"\n"+claim+"\n"+wrapper[1]+"\n\nwrapped one\nwrapped two\n"),
			1,
			"%s renders as markup a reader sees, so a claim inside it is a visible one anybody can type",
			name,
		)
	}
}

// TestAByteOrderMarkNeverHidesAGeneratedClaim pins the strip that runs before
// anything reads the text.
//
// It is a property of the READ rather than a clause of the rule, so nothing
// else in this repository would ever demand a case — and pointing the constant
// at a prefix no document carries (U+FFFE for U+FEFF) left `make check` at exit
// 0 and total coverage 100.0%. Driven as a built binary the mutant differs on
// exactly the input the constant exists for: with the mark still in place the
// first block is a PARAGRAPH rather than an HTML comment, so the claim is not a
// claim and the whole file gains findings it should not have. The test is the
// mutation, and until now nothing failed under it. Found by an adversarial
// review.
func TestAByteOrderMarkNeverHidesAGeneratedClaim(t *testing.T) {
	t.Parallel()

	const claim = "<!-- Code generated by tool. DO NOT EDIT. -->"

	assert.Empty(t, analyze(t, "api.md", "\ufeff"+claim+"\n\nwrapped one\nwrapped two\n"),
		"the mark is stripped before the parse, so the claim is still the document's first block")
	assert.Len(t, analyze(t, "api.md", "\ufeff"+"wrapped one\nwrapped two\n"), 1,
		"and stripping it takes nothing else with it")
}
