package hardwrap

// The generated-document exemption: the one way out of this rule, and so the
// one place an evasion is worth the most.
//
// A generated document cannot be fixed by editing it — the next run overwrites
// the edit — so reporting one tells an author to change a file that is not
// theirs to change. The exemption is therefore real, and it is also the whole
// attack surface: anything that lets a line of ordinary text claim generated
// authorship is a one-line, audit-trail-free opt-out from every finding in the
// file.
//
// It is closed by asking the PARSER rather than the text. A claim counts only
// when it sits in an HTML comment block, which is the only construct markdown
// renders as nothing at all. A document DEMONSTRATING the convention shows the
// same words inside a fence or a paragraph, and those are different nodes — a
// fenced code block and a paragraph — so a document about generated headers is
// still judged as the hand-written document it is.

import (
	"regexp"

	"github.com/yuin/goldmark/ast"
)

// generatedClaim is the conventional statement a generator makes about its own
// output.
//
// The claim must be a claim of AUTHORSHIP, not merely a request not to edit. A
// bare "DO NOT EDIT" is something any author can type, and a file that invites
// manual additions is hand-maintained by design; "Code generated … DO NOT EDIT"
// and "@generated" are what tools write about their own output. The trailing
// period is optional and the generator's own words may follow, because that is
// how the generators actually spell it — gomarkdoc writes
// `<!-- Code generated by gomarkdoc. DO NOT EDIT -->`, with no period.
var generatedClaim = regexp.MustCompile(`Code generated .*DO NOT EDIT|@generated`)

// generatedHeader is how far into a document a claim is looked for. A generator
// writes its claim at the top; a comment further down is a note about a
// passage, not a statement about the file.
const generatedHeader lineNumber = 5

// isGenerated reports a document that declares itself a generator's output.
func isGenerated(document ast.Node, source []byte, lines lineIndex) bool {
	for child := document.FirstChild(); child != nil; child = child.NextSibling() {
		if declaresGenerated(child, source, lines) {
			return true
		}
	}
	return false
}

// declaresGenerated reports one top-level block that IS a generator's claim.
//
// Three things have to hold together, and each one closes a way in: the block
// is an HTML comment (a paragraph saying the same words is text a reader sees),
// it begins within the header (a document quoting the convention halfway down
// is describing it), and it carries the claim.
func declaresGenerated(node ast.Node, source []byte, lines lineIndex) bool {
	block, isHTML := node.(*ast.HTMLBlock)
	if !isHTML || block.Lines().Len() == 0 {
		return false
	}
	if block.HTMLBlockType == ast.HTMLBlockType2 && lines.of(byteOffset(block.Lines().At(0).Start)) <= generatedHeader {
		return generatedClaim.Match(block.Lines().Value(source))
	}
	return false
}
